# Generated by Django 5.1.6 on 2025-04-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
