# Generated by Django 5.1.7 on 2025-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_delete_userdata_alter_userprofile_pno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('rankOf', models.CharField(max_length=1, null=True)),
                ('userType', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'ranks',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
