# Generated by Django 5.1.6 on 2025-05-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_delete_userdata_alter_userprofile_pno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftUnserviceable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.CharField(max_length=100)),
                ('af_hours', models.CharField(max_length=100)),
                ('how_found', models.CharField(max_length=100)),
                ('snow', models.CharField(max_length=100)),
                ('defect_code', models.CharField(max_length=100)),
                ('reason_us', models.TextField(max_length=100)),
                ('limitation', models.BooleanField(default=False)),
                ('deferred_defect', models.BooleanField(default=False)),
                ('husbandry', models.BooleanField(default=False)),
                ('concession', models.BooleanField(default=False)),
                ('discovered_by', models.BooleanField(max_length=100)),
                ('auth_code', models.BooleanField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pno',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(max_length=50),
        ),
    ]
