# Generated by Django 5.1.7 on 2025-05-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_ranks_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=30, null=True)),
                ('qual', models.CharField(max_length=50, null=True)),
                ('user_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'quals',
            },
        ),
        migrations.RenameField(
            model_name='ranks',
            old_name='rankOf',
            new_name='rank_of',
        ),
        migrations.RenameField(
            model_name='ranks',
            old_name='userType',
            new_name='user_type',
        ),
    ]
