# Generated by Django 5.1.6 on 2025-05-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_aircraftunserviceable_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftunserviceable',
            name='concession',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftunserviceable',
            name='deferred_defect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftunserviceable',
            name='husbandry',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftunserviceable',
            name='limitation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
