# Generated by Django 5.1.6 on 2025-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_quals_rename_rankof_ranks_rank_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftMasters',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('side_no', models.CharField()),
                ('aircraft_mark', models.CharField(blank=True, null=True)),
                ('aircraft_type_id', models.BigIntegerField(blank=True, null=True)),
                ('airframe_serial_no', models.CharField(blank=True, null=True)),
                ('date_of_acceptance', models.DateField(blank=True, null=True)),
                ('date_of_manufacture', models.DateField(blank=True, null=True)),
                ('date_of_expiry_of_warranty', models.DateField(blank=True, null=True)),
                ('basic_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_auw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_landing_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_combat_load', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_operating_gg_load', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_denomination', models.CharField(blank=True, null=True)),
                ('max_fuel_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_denomination', models.CharField(blank=True, null=True)),
                ('max_takeoff_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_landing_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed_unit', models.CharField(blank=True, null=True)),
                ('active_yn', models.CharField(blank=True, null=True)),
                ('max_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('primary_role', models.CharField(blank=True, null=True)),
                ('secondary_role', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aircraft_masters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=40)),
                ('sub_customer_name', models.CharField(max_length=40)),
                ('customer_type', models.CharField(max_length=3)),
                ('cust_prefix', models.CharField(max_length=6)),
                ('addressee', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('parent_unit_id', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('active_yn', models.CharField(max_length=1)),
                ('repair_agency', models.CharField(blank=True, max_length=1, null=True)),
                ('dba_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('date_dba_remarks', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuelTanks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tank_group', models.CharField(blank=True, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('denominations', models.CharField(blank=True, null=True)),
                ('aircraft_type_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fuel_tanks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=50)),
                ('rank_id', models.DecimalField(blank=True, decimal_places=0, max_digits=64, null=True)),
                ('customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=64, null=True)),
                ('login_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('pwd_date_updated', models.DateField(blank=True, null=True)),
                ('pwd_valid_upto', models.DateField(blank=True, null=True)),
                ('pin', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('pin_date_updated', models.DateField(blank=True, null=True)),
                ('pin_valid_upto', models.DateField(blank=True, null=True)),
                ('fsi_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('active_yn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
