# Generated by Django 5.2.1 on 2025-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_aircraftunserviceable_concession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('sub_customer_name', models.CharField(max_length=40)),
                ('customer_type', models.CharField(max_length=3)),
                ('cust_prefix', models.CharField(max_length=6)),
                ('addressee', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('parent_unit_id', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('active_yn', models.CharField(default='Y', max_length=1)),
                ('repair_agency', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('dba_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('date_dba_remarks', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Quals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=30, null=True)),
                ('qual', models.CharField(max_length=50, null=True)),
                ('user_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'quals',
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('rank_of', models.CharField(max_length=1, null=True)),
                ('user_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'ranks',
            },
        ),
        migrations.DeleteModel(
            name='AircraftUnserviceable',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
