# Generated by Django 5.1.6 on 2025-05-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_aircraftmasters_customers_fueltanks_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='customer_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='login_pwd',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='rank_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
